### ISSUE TITLE
Username takes a while to show up on front page

### ISSUE THREAD

**Issue by Turtle84375** [Scratchblox-Official/scratchblox#1]
When logged in, a simple home screen now shows some information, including a login button and the logged in user's username. However, it takes a little waiting & refreshing for the username to properly show up. Anyone have any ideas for how we can make this happen faster, or even better, is there already an attribute that stores the username that we can just reference there?

**Comment by Turtle84375** [comment]
I found this to be, in a way, linked to another problem, sometimes when initially visiting https://scratchblox.tk, I get a blank screen, even though it's supposed to redirect to https://web.scratchblox.tk and subsequently https://web.scratchblox.tk/home. Again, it takes a whole lot of refreshing and waiting to get it to do what it's supposed to do. Raising priority to high, this issue is linked to main site access and performance.

**Comment by Ancoder2009** [comment]
Ok i will shut down the whole site all assets will be moved i will reprogram the site

**Comment by Turtle84375** [comment]
> Ok i will shut down the whole site all assets will be moved i will reprogram the site

Got it.
