### ISSUE TITLE
not related, but

### ISSUE THREAD

**Issue by CodeGuy92** [Scratchblox-Official/scratchblox#13]
How tf do you create a token authentication system, i've been trying to figure this out for **2 fking months**

**Comment by Bubalo1234** [comment]
1. Uh please be clean i misread that as the actual f-word
2. If this is what you mean, maybe use cloud lists? Pretty sure there are a bunch of tutorials online.
3. If that is not what you mean, if you set var to 1, next time the person comes it will still be 1. (at least what I know of it.)
