### ISSUE TITLE
User Accounts Not Saved to Database

### ISSUE THREAD

**Issue by Turtle84375** [Scratchblox-Official/scratchblox#5]
When a user creates an account, their account is retained for a short while, likely via some cookie or cache item, and I found that I was able to log in and out of 2 accounts I created with ease, and even cleared the cache and cookies several times in between, and still was able to properly log into my testing accounts. However, as I suspected earlier, the account information doesn't seem to be saving anywhere. When I went to log into my account about an hour later, it said that it couldn't find my account. If I understand the system correctly, it seems that the account information in all held in the file db.db in the repository "backendauthapi." It doesn't look like any changes are being made to the file when accounts are created, so there's obviously some sort of problem with the communication between that database and the POST requests. @Ancoder2009 , I believe you created the system, do you have any idea how to fix this? I see you managed to create your own account using SQlite in the db.db file, so you are probably more experienced than me in this.

This should preferably be high priority, as the login system is essential to the site's function.

**Comment by Turtle84375** [comment]
I was notified that this is because the server isn't always on... this is an issue.

**Comment by Ancoder2009** [comment]
Its saves noting is wrong
i tested

**Comment by Turtle84375** [comment]
> Its saves noting is wrong
> i tested

I'll test it again in a few hours, and then again at the end of the day. My problem was that it would be fine for a while, then not be fine a while later.

**Comment by Turtle84375** [comment]
Closing in lieu of full site backend remake.
