### ISSUE TITLE
Anyone wanna try to get the stylesheet to work for the login/register pages?

### ISSUE THREAD

**Issue by Turtle84375** [Scratchblox-Official/scratchblox#6]
Currently, style.css works everywhere but the login pages, anyone want to try and fix that?

**Comment by RodolfoNei** [comment]
Hi! I think I know what is the problem, can I work on this?

**Comment by Turtle84375** [comment]
> Hi! I think I know what is the problem, can I work on this?

Thank you for the offer! You should be able to create a pull request, feel free to edit the style.css file and request a merge of your edits, and either I or another Developer will review and/or merge your commit.

**Comment by Turtle84375** [comment]
Successfully merged.
