### ISSUE TITLE
I cannot sign in

### ISSUE THREAD

**Issue by NILL2021** [Scratchblox-Official/scratchblox#9]
it says a server issue
Also pls invite me to repo

**Comment by Turtle84375** [comment]
> it says a server issue
> Also pls invite me to repo

Please refer to #1, the server is currently turned off.

On another note, I will send you the organization invite.

**Comment by Turtle84375** [comment]
> On another note, I will send you the organization invite.

@NILL2021 Just realized the issue, I have moved up the organization base permission from `read` to `write`, so you should now be able to commit.
